name: mdmix-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - scipy>=1.7.0
  - cftime
  - ambertools
  - netCDF4>=1.6.0
  - biopython>=1.79
  - griddataformats>=1.0.0
